index:
    path: /
    defaults: { _controller: 'App\Controller\SecurityController::login' }

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /admin

logout:
    path: /home/logout
